# Generated by Django 3.0.2 on 2020-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('room_value', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('apartment_foo', models.ImageField(blank=True, upload_to='apartment')),
            ],
        ),
    ]
