# Generated by Django 3.0.2 on 2020-06-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('room_value', models.CharField(max_length=100)),
                ('description_title', models.TextField(blank=True)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ToBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(db_index=True)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/apartment')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kedr.Apartment')),
            ],
        ),
    ]
