# Generated by Django 3.0.2 on 2020-01-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_foo',
            field=models.ImageField(blank=True, upload_to='media/apartment'),
        ),
    ]
