# Generated by Django 3.0.2 on 2020-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0002_auto_20200130_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/apartment')),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_foo',
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_obj',
            field=models.ManyToManyField(to='kedr.Photo'),
        ),
    ]
