# Generated by Django 3.0.2 on 2020-01-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0004_auto_20200131_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='apartment_obj',
            field=models.ManyToManyField(related_name='images', to='kedr.Apartment'),
        ),
    ]
