# Generated by Django 3.0.2 on 2020-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0006_auto_20200131_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_title',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
