# Generated by Django 3.0.2 on 2020-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0007_auto_20200131_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('phone_number', models.IntegerField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
