# Generated by Django 3.0.2 on 2020-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0008_tobook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobook',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
