# Generated by Django 3.0.2 on 2020-02-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kedr', '0009_auto_20200203_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tobook',
            name='slug',
        ),
    ]
